### ISSUE TITLE
only disable strict mode

### ISSUE THREAD

**Issue by taak77** [fancyboynet/babel-preset-es2015-without-strict#1]
Hi,

it seems this module was created as a result of https://phabricator.babeljs.io/T6660 and drops `babel-plugin-transform-es2015-modules-commonjs` module entirely.
Is it really the intent of this module?

I tried to use this module with babel 6 and now I get compile errors for the code which compiles fine with the default es2015 preset.

If you want to just disable strict mode, don't you want to pass `{strict: false}` to `babel-plugin-transform-es2015-modules-commonjs`?

**Comment by fancyboynet** [comment]
@taak77 yes, I just want to disable the strict mode, but I did not find any way to do that. Thanks for the tip, but it seem not work unfortunately.
The config I tried is:

```
{
  "presets": ["es2015"],
  "plugins": [
      ["transform-es2015-modules-commonjs", {
          "strict" : false
      }]
  ],
  "ignore": ["node_modules/**/*"]
}
```

Anything wrong?

**Comment by taak77** [comment]
Similar to how https://github.com/bkonkle/babel-preset-es2015-loose does,
can you try this?

```
var modify = require('modify-babel-preset');

module.exports = modify('es2015', {
    'transform-es2015-modules-commonjs': {strict: false}
});
```

**Comment by fancyboynet** [comment]
Thanks,I just updated the plugin and added the 'babel-plugin-transform-es2015-modules-commonjs' again, can you update the package and retry ?

**Comment by taak77** [comment]
It works now for me. Thanks!

**Comment by fancyboynet** [comment]
With pleasure.
